"""
Django settings for etcl project.

Generated by 'django-admin startproject' using Django 1.8.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import os
#import logging
#import ldap

from django.utils.translation import ugettext_lazy as _

#from django_auth_ldap.config import LDAPSearch, MemberDNGroupType

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/
SECRET_KEY = 'j8dwfg6kvg=fnfs33s0x(t&0pfe)p9$3dm943)6hvurj6@=+4j'
DEBUG = True
ALLOWED_HOSTS = []
INTERNAL_IPS = ['127.0.0.1']
WSGI_APPLICATION = 'etcl.wsgi.application'


# Application definition

INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'proposals',
    'reviews',
    'feedback',

    'easy_pdf',

    'django.contrib.admin',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ROOT_URLCONF = 'etcl.urls'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    #'mysql': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'ethics',
    #    'USER': 'root',
    #    'PASSWORD': 'root++',
    #}
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'nl-NL'
LANGUAGES = (
    ('nl', _('Nederlands')),
    ('en', _('Engels')),
)
USE_I18N = True
USE_L10N = True
LOCALE_PATHS = (
    'locale',
)

TIME_ZONE = 'Europe/Amsterdam'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Authentication (via LDAP)

LOGIN_REDIRECT_URL = '/'

#AUTH_LDAP_SERVER_URI = 'ldap://ldap.forumsys.com'
#AUTH_LDAP_BIND_DN = 'cn=read-only-admin,dc=example,dc=com'
#AUTH_LDAP_BIND_PASSWORD = 'password'
#AUTH_LDAP_USER_DN_TEMPLATE = 'uid=%(user)s,dc=example,dc=com'
#AUTH_LDAP_USER_ATTR_MAP = {
#    'first_name': 'uid',
#    'last_name': 'sn'
#}
#AUTH_LDAP_ALWAYS_UPDATE_USER = False

AUTHENTICATION_BACKENDS = (
    # 'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)
#AUTH_LDAP_SERVER_URI = 'ldap://ldap.hum.uu.nl'
#AUTH_LDAP_START_TLS = True
#AUTH_LDAP_BIND_DN = ''
#AUTH_LDAP_BIND_PASSWORD = ''

# Group search; doesn't seem to work
#AUTH_LDAP_GROUP_SEARCH = LDAPSearch('ou=groups,dc=uu,dc=nl', ldap.SCOPE_SUBTREE)
#AUTH_LDAP_GROUP_TYPE = MemberDNGroupType('memberuid')
#AUTH_LDAP_REQUIRE_GROUP = 'cn=GG_GW_UiL-OTS_Labs_AllUsers,ou=groups,dc=uu,dc=nl'

#AUTH_LDAP_USER_SEARCH = LDAPSearch('dc=uu,dc=nl', ldap.SCOPE_SUBTREE, '(uid=%(user)s)')
#AUTH_LDAP_USER_ATTR_MAP = {
#    'first_name': 'givenName',
#    'last_name': 'humAchternaam',
#    'email': 'mail'
#}

# LDAP logging
#logger = logging.getLogger('django_auth_ldap')
#logger.addHandler(logging.StreamHandler())
#logger.setLevel(logging.DEBUG)

# File handling
MEDIA_ROOT = 'media'

# E-mail settings
EMAIL_HOST = 'localhost'
EMAIL_PORT = 1025
EMAIL_FROM = 'M.H.vanderKlis@uu.nl'

# Group names
GROUP_SECRETARY = 'Secretaris'
GROUP_COMMISSION = 'Commissie'
