# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_auto_20180822_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='version',
            field=models.PositiveIntegerField(default=2, verbose_name='INTERNAL - Describes which version of the intervention model is used'),
        ),
    ]
