# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0008_auto_20180822_1307"),
    ]

    operations = [
        migrations.AddField(
            model_name="observation",
            name="is_anonymous_details",
            field=models.TextField(blank=True, verbose_name="Licht toe"),
        ),
        migrations.AddField(
            model_name="observation",
            name="is_in_target_group_details",
            field=models.TextField(blank=True, verbose_name="Licht toe"),
        ),
        migrations.AddField(
            model_name="observation",
            name="is_nonpublic_space_details",
            field=models.TextField(blank=True, verbose_name="Licht toe"),
        ),
    ]
