# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observations", "0010_auto_20180822_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="details_frequency",
            field=models.TextField(
                blank=True,
                help_text="Bijvoorbeeld: De leraar zal 5 lessen van 45 minuten worden geobserveerd.",
                verbose_name="Beschrijf <b>hoe vaak en hoe lang</b> de observant wordt geobserveerd.",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="details_who",
            field=models.TextField(
                blank=True,
                help_text="Maak duidelijk voor de commissie wie er wordt geobserveerd en wat er precies van de deelnemer wordt geobserveerd. Bijvoorbeeld: De leraar zal geobserveerd worden. De observatie moet de interactie tussen leraar en leerling in kaart brengen.",
                verbose_name="Beschrijf <b>wie</b> er wordt geobserveerd.",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="details_why",
            field=models.TextField(
                blank=True,
                help_text="Wat is het doel van de observatie? Bijvoorbeeld: Het doel van de observatie is inzicht te krijgen in hoe de leerkracht omgaat met de uitleg van de nieuwe lesmethode. Doet h/zij dat op de gewenste manier en in begrijpelijke taal?",
                verbose_name="Beschrijf <b>waarom</b> er wordt geobserveerd.",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="leader_has_coc",
            field=models.NullBooleanField(
                help_text='Iedereen die op een school werkt moet in het bezit         zijn van een Verklaring Omtrent Gedrag (VOG, zie         <a href="https://www.justis.nl/producten/vog/"         target="_blank">https://www.justis.nl/producten/vog/</a>).         Het is de verantwoordelijkheid van de school om hierom te vragen.         De FETC-GW neemt hierin een adviserende rol en wil de onderzoekers         waarschuwen dat de school om een VOG kan vragen.',
                verbose_name="Is de testleider in het bezit van een VOG?",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="setting",
            field=models.ManyToManyField(
                blank=True,
                to="main.Setting",
                verbose_name="Geef aan waar de dataverzameling plaatsvindt",
            ),
        ),
    ]
