# Generated by Django 2.2.24 on 2021-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0014_auto_20200428_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='details_why',
            field=models.TextField(blank=True, help_text='Wat is het doel van de observatie? Bijvoorbeeld: Het doel van de observatie is inzicht te krijgen in hoe de leerkracht omgaat met de uitleg van de nieuwe lesmethode. Doet die dat op de gewenste manier en in begrijpelijke taal?', verbose_name='Beschrijf <b>waarom</b> er wordt geobserveerd.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='needs_approval',
            field=models.BooleanField(default=False, verbose_name='Heb je toestemming nodig van een (samenwerkende) instantie om deze observatie te mogen uitvoeren?'),
        ),
    ]
