# Generated by Django 3.2.13 on 2022-08-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_alter_observation_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='registrations',
            field=models.ManyToManyField(to='observations.Registration', verbose_name='Hoe wordt het gedrag geregistreerd?'),
        ),
    ]
