# Generated by Django 4.2.11 on 2024-11-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0016_alter_observation_registrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="is_nonpublic_space",
            field=models.BooleanField(
                default=False,
                help_text="Bijvoorbeeld er wordt geobserveerd bij iemand thuis, tijdens een hypotheekgesprek, tijdens politieverhoren of een digitale omgeving waar een account voor moet worden aangemaakt.",
                verbose_name="Wordt er geobserveerd in een niet-openbare ruimte?",
            ),
        ),
    ]
