# Generated by Django 4.2.11 on 2024-11-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0017_alter_observation_is_nonpublic_space"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="has_advanced_consent",
            field=models.BooleanField(
                default=True, verbose_name="Wordt er van tevoren toestemming gegeven?"
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="has_advanced_consent_details",
            field=models.TextField(
                blank=True,
                verbose_name="Leg uit waarom er niet van tevoren toestemming wordt gegeven en beschrijf ook op welke wijze dit achteraf verzorgd wordt.",
            ),
        ),
    ]
