# Generated by Django 4.2.11 on 2024-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0017_alter_observation_has_advanced_consent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_recording",
            field=models.BooleanField(default=False),
        ),
    ]
