# Generated by Django 4.2.11 on 2024-12-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0018_alter_observation_has_advanced_consent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="details_frequency",
            field=models.TextField(
                blank=True,
                help_text="Bijvoorbeeld: De leraar zal 5 lessen van 45 minuten worden geobserveerd.",
                verbose_name="Beschrijf <b>hoe vaak en hoelang</b> de observant wordt geobserveerd.",
            ),
        ),
    ]
