# Generated by Django 4.2.11 on 2024-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0018_alter_observation_has_advanced_consent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="has_advanced_consent",
            field=models.BooleanField(
                default=True,
                verbose_name="Gaan deelnemers van tevoren akkoord met de observatie?",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="has_advanced_consent_details",
            field=models.TextField(
                blank=True,
                verbose_name="Leg uit waarom er niet van tevoren akkoord kan worden gegeven en beschrijf ook op welke wijze dit achteraf verzorgd wordt.",
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="Bijvoorbeeld: je maakt aantekeningen van observaties van onbekenden in de openbare ruimte (anoniem) of je maakt video-opnamen van gedragingen van mensen (niet anoniem).",
                verbose_name="Wordt er anoniem geobserveerd?",
            ),
        ),
    ]
