# Generated by Django 4.2.11 on 2025-03-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0019_alter_observation_details_frequency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="registrations",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="registrations_details",
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
