# Generated by Django 4.2.11 on 2024-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interventions", "0009_alter_intervention_has_controls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="period",
            field=models.TextField(
                blank=True,
                verbose_name="Wat is de periode waarbinnen de interventie plaatsvindt?",
            ),
        ),
    ]
