language: python

dist: bionic

python:
    - 3.6

before_install:
  - sudo apt-get install poppler-utils poppler-data libpoppler-cpp-dev

install:
    - pip install -U pip
    - pip install -r requirements.txt

script:
    - python manage.py test
