# Generated by Django 3.2.14 on 2022-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210528_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='systemmessage',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='systemmessage',
            name='message_nl',
            field=models.TextField(null=True),
        ),
    ]
