# Generated by Django 3.2.20 on 2023-10-05 14:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0008_auto_20220926_0929"),
    ]

    operations = [
        migrations.CreateModel(
            name="SamlUserProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_nl", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("saml_name", models.CharField(max_length=255)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="faculties", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
