# Generated by Django 3.2.20 on 2023-10-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_faculty_samluserproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='is_privileged',
            field=models.BooleanField(default=False),
        ),
    ]
