# Generated by Django 3.2.20 on 2023-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_faculty_samluserproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='internal_name',
            field=models.CharField(choices=[('humanities', 'Humanities'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
