# Generated by Django 4.2.11 on 2024-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_faculty_internal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="gatekeeper_documents",
            field=models.PositiveIntegerField(
                choices=[(1, "No"), (2, "Optional"), (3, "Required")],
                default=1,
                verbose_name="Gatekeeper documents",
            ),
        ),
    ]
