# Generated by Django 4.2.11 on 2024-12-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_setting_gatekeeper_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="is_school",
            field=models.BooleanField(default=False, verbose_name="Is a school"),
        ),
    ]
