# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-24 14:33
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0017_proposal_reviewing_committee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='funding',
            field=models.ManyToManyField(blank=True, to='proposals.Funding', verbose_name='Hoe wordt dit onderzoek gefinancierd?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.Relation', verbose_name='In welke hoedanigheid bent u betrokken bij deze UiL OTS studie?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='reviewing_committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='Door welke comissie dient deze studie te worden beoordeeld?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='summary',
            field=models.TextField(blank=True, validators=[core.validators.MaxWordsValidator(200)], verbose_name='Geef een duidelijke, bondige beschrijving van de onderzoeksvraag of -vragen. Gebruik maximaal 200 woorden.'),
        ),
    ]
