# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0019_auto_20190401_1343"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="institution",
            name="description_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="description_nl",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
