# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0021_auto_20190926_1559"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="title",
            field=models.CharField(
                help_text="De titel die u hier opgeeft is zichtbaar voor de FETC-GW-leden en, wanneer de studie is goedgekeurd, ook voor alle medewerkers die in het archief van deze portal kijken. De titel mag niet identiek zijn aan een vorige titel van een studie die u heeft ingediend.",
                max_length=200,
                verbose_name="Wat is de titel van uw studie? Deze titel zal worden gebruikt in alle formele correspondentie.",
            ),
        ),
    ]
