# Generated by Django 2.2.17 on 2020-12-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0024_remove_wmo_is_behavioristic'),
        ('proposals', '0023_auto_20200428_1337'),
    ]

    operations = [
    ]
