# Generated by Django 2.2.20 on 2021-05-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0031_auto_20210201_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='avg_understood',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
