# Generated by Django 2.2.20 on 2021-05-21 09:54

from django.db import migrations, models
import main.validators
import proposals.utils.proposal_utils


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0032_proposal_avg_understood'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='dmp_file',
            field=models.FileField(blank=True, storage=proposals.utils.proposal_utils.OverwriteStorage(), upload_to=proposals.utils.proposal_utils.FilenameFactory('DMP'), validators=[main.validators.validate_pdf_or_doc], verbose_name='Als u een Data Management Plan heeft voor deze studie, kunt u kiezen om deze hier bij te voegen. Het aanleveren van een DMP vergemakkelijkt het toetsingsproces aanzienlijk.'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='avg_understood',
            field=models.BooleanField(default=False),
        ),
    ]
