# Generated by Django 3.2.13 on 2022-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0035_auto_20220607_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="self_assesment",
            field=models.TextField(
                blank=True,
                max_length=500,
                verbose_name="Wat zijn de belangrijkste ethische kwesties in dit onderzoek en beschrijf kort hoe ga je daarmee omgaat.",
            ),
        ),
    ]
