# Generated by Django 3.2.13 on 2022-08-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0038_auto_20220830_1357"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentContext",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(unique=True)),
                ("description", models.CharField(max_length=200)),
                ("description_nl", models.CharField(max_length=200, null=True)),
                ("description_en", models.CharField(max_length=200, null=True)),
                ("needs_details", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="proposal",
            name="student_context",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="proposals.studentcontext",
                verbose_name="In welke context doe je dit onderzoek?",
            ),
        ),
    ]
