# Generated by Django 3.2.13 on 2022-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0038_auto_20220826_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='student_program',
            field=models.CharField(blank=True, max_length=200, verbose_name='Wat is je studierichting?'),
        ),
    ]
