# Generated by Django 3.2.14 on 2022-10-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0042_proposal_student_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='date_start',
            field=models.DateField(blank=True, help_text='NB: Voor een aanvraag van een onderzoek dat al gestart is voordat de FETC-GW de aanvraag heeft goedgekeurd kan geen formele goedkeuring meer gegeven worden; de FETC-GW geeft in die gevallen een post-hoc advies.', null=True, verbose_name='Wat is de beoogde startdatum van het onderzoek waarvoor deze aanvraag wordt ingediend?'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='student_justification',
            field=models.TextField(blank=True, max_length=500, verbose_name='Studenten (die mensgebonden onderzoek uitvoeren binnen hun studieprogramma) hoeven in principe geen aanvraag in te dienen bij de FETC-GW. Bespreek met je begeleider of je daadwerkelijk een aanvraag moet indienen. Als dat niet hoeft kun je nu je aanvraag afbreken. Als dat wel moet, geef dan hier aan wat de reden is:'),
        ),
    ]
