# Generated by Django 3.2.18 on 2023-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0046_auto_20230627_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='translated_forms',
            field=models.BooleanField(default=None, verbose_name='Worden de informed consent formulieren nog vertaald naar een andere taal dan Nederlands of Engels?'),
        ),
    ]
