# Generated by Django 3.2.18 on 2023-07-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0046_auto_20230710_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='embargo',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Als je deelnemers van je onderzoek moeten worden misleid, kan           je ervoor kiezen je applicatie pas later op te laten nemen in het           semi-publieke archief. Wil je dat jouw onderzoek tijdelijk onder           embargo wordt geplaatst?'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='embargo_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Vanaf welke datum mag je onderzoek wel in het archief worden weergegeven?'),
        ),
    ]
