# Generated by Django 3.2.18 on 2023-06-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0047_alter_proposal_translated_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='translated_forms',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Worden de informed consent formulieren nog vertaald naar een andere taal dan Nederlands of Engels?'),
        ),
    ]
