# Generated by Django 3.2.18 on 2023-07-13 13:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0047_auto_20230710_1235'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proposal',
            managers=[
                ('archived_proposals', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='public',
        ),
    ]
