# Generated by Django 3.2.18 on 2023-07-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0048_alter_proposal_translated_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='translated_forms_languages',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Andere talen:'),
        ),
    ]
