# Generated by Django 3.2.23 on 2023-11-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0049_alter_proposal_supervisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="other_applicants",
            field=models.BooleanField(
                default=False,
                help_text='Werk je samen met een onderzoeker of organisatie buiten de UU en is je onderzoek niet strikt anoniem? Neem dan contact op met de <a href="mailto:privacy.gw@uu.nl">privacy officer</a>. Er moeten dan wellicht afspraken worden gemaakt over de verwerking van persoonsgegevens.',
                verbose_name="Zijn er nog andere onderzoekers bij deze aanvraag betrokken die geaffilieerd zijn aan één van de onderzoeksinstituten ICON, OFR, OGK of ILS?",
            ),
        ),
    ]
