# Generated by Django 3.2.18 on 2023-07-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0049_alter_proposal_translated_forms_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='translated_forms_languages',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Andere talen:'),
        ),
    ]
