# Generated by Django 3.2.20 on 2023-11-15 10:56

from django.db import migrations, models
import proposals.validators


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0049_alter_proposal_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='avg_understood',
            field=models.BooleanField(blank=True, default=None, null=True, validators=[proposals.validators.AVGUnderstoodValidator], verbose_name='Ik heb mijn aanvraag en de documenten voor deelnemers besproken met de privacy officer.'),
        ),
    ]
