# Generated by Django 3.2.23 on 2023-11-21 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0050_alter_proposal_other_applicants"),
        ("proposals", "0050_auto_20231116_1413"),
    ]

    operations = []
