# Generated by Django 3.2.23 on 2024-02-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proposals", "0052_alter_proposal_studies_similar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="other_stakeholders",
            field=models.BooleanField(
                default=False,
                verbose_name="Zijn er nog andere onderzoekers bij deze aanvraag betrokken die <strong>niet</strong> geaffilieerd zijn aan een van de onderzoeksinstituten van de Faculteit Geestwetenschappen van de UU? Zoja, vermeld diens naam en affiliatie.",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="stakeholders",
            field=models.TextField(
                blank=True, verbose_name="Naam en affiliatie van andere betrokkenen"
            ),
        ),
    ]
