# Generated by Django 3.2.17 on 2024-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20240315_1342'),
        ('proposals', '0053_auto_20240201_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='attachments.Attachment'),
        ),
    ]
