# Generated by Django 4.2.11 on 2024-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0054_proposal_knowledge_security_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="other_applicants",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text='Werk je samen met een onderzoeker of organisatie buiten de UU en is je onderzoek niet strikt anoniem? Neem dan contact op met de <a href="mailto:privacy.gw@uu.nl">privacy officer</a>. Er moeten dan wellicht afspraken worden gemaakt over de verwerking van persoonsgegevens.',
                verbose_name="Zijn er nog andere onderzoekers bij deze aanvraag betrokken die geaffilieerd zijn aan één van de onderzoeksinstituten ICON, OFR, OGK of ILS?",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="other_stakeholders",
            field=models.BooleanField(
                blank=True,
                default=None,
                verbose_name="Zijn er nog andere onderzoekers bij deze aanvraag betrokken die <strong>niet</strong> geaffilieerd zijn aan een van de onderzoeksinstituten van de Faculteit Geestwetenschappen van de UU? Zoja, vermeld diens naam en affiliatie.",
            ),
        ),
    ]
