# Generated by Django 4.2.11 on 2024-12-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0056_alter_proposal_other_applicants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="studies_similar",
            field=models.BooleanField(
                blank=True,
                help_text="Daar waar de verschillen klein en qua belasting of risico irrelevant zijn is sprake van in essentie hetzelfde traject. Let op: als verschillende groepen deelnemers verschillende <i>soorten</i> taken krijgen, dan zijn dit afzonderlijke trajecten.",
                null=True,
                verbose_name="Doorlopen alle deelnemers hetzelfde onderzoekstraject, zonder noemenswaardige verschillen in taken en belasting?",
            ),
        ),
    ]
