# Generated by Django 4.2.11 on 2024-12-17 15:33

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0057_alter_proposal_studies_similar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="other_applicants",
            field=models.BooleanField(
                default=None,
                null=True,
                verbose_name="Zijn er nog andere onderzoekers bij deze aanvraag betrokken die geaffilieerd zijn aan één van de onderzoeksinstituten ICON, OFR, OGK of ILS?",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="other_stakeholders",
            field=models.BooleanField(
                default=None,
                help_text='Werk je samen met een onderzoeker of organisatie buiten de UU en is je onderzoek niet strikt anoniem? Neem dan contact op met de <a href="mailto:privacy.gw@uu.nl">privacy officer</a>. Er moeten dan wellicht afspraken worden gemaakt over de verwerking van persoonsgegevens.',
                null=True,
                verbose_name="Zijn er nog andere onderzoekers bij deze aanvraag betrokken die <strong>niet</strong> geaffilieerd zijn aan een van de onderzoeksinstituten van de Faculteit Geestwetenschappen van de UU? Zoja, vermeld diens naam en affiliatie.",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="self_assessment",
            field=models.TextField(
                blank=True,
                validators=[main.validators.MaxWordsValidator(1000)],
                verbose_name="Wat zijn de belangrijkste ethische kwesties in dit onderzoek en beschrijf kort hoe je daarmee omgaat. Gebruik maximaal 1000 woorden.",
            ),
        ),
    ]
