# Generated by Django 4.2.20 on 2025-04-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0058_alter_proposal_other_applicants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="funding_name",
            field=models.CharField(
                blank=True,
                help_text="De titel die je hier opgeeft zal in de formele goedkeuringsbrief gebruikt worden.",
                max_length=200,
                verbose_name="Wat is de naam van het gefinancierde project en wat is het projectnummer?",
            ),
        ),
    ]
