# Generated by Django 4.2.20 on 2025-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0059_alter_proposal_funding_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="data_manager",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Ik heb mijn datamanagementplan (DMP) besproken met de data manager van de Faculteit Geesteswetenschappen.",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="research_data_management",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Ik heb mijn datamanagementplan (DMP) besproken met iemand van Research Data Management Support.",
            ),
        ),
    ]
