# Generated by Django 4.2.20 on 2025-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0059_alter_proposal_funding_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="privacy_officer",
            new_name="privacy_officer_conversation",
        ),
        migrations.AddField(
            model_name="proposal",
            name="data_manager_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Als je geen Data Management Plan indient bij deze aanvraag, beantwoord deze vraag dan met 'nee'.",
                null=True,
                verbose_name="Ik heb mijn Data Management Plan (DMP) besproken met de data manager van de faculteit Geesteswetenschappen.",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="research_data_management_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Als je geen Data Management Plan indient bij deze aanvraag, beantwoord deze vraag dan met 'nee'.",
                null=True,
                verbose_name="Ik heb mijn Data Management Plan (DMP) besproken met iemand van Research Data Management Support.",
            ),
        ),
    ]
