# Generated by Django 4.2.20 on 2025-05-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proposals",
            "0060_rename_privacy_officer_proposal_privacy_officer_conversation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="data_manager_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Als je geen Data Management Plan indient bij deze aanvraag, beantwoord deze vraag dan met 'nee'.",
                null=True,
                verbose_name="Ik heb mijn Data Management Plan (DMP) besproken met de data manager van de faculteit Geesteswetenschappen.",
            ),
        ),
    ]
