# Generated by Django 4.2.20 on 2025-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0060_proposal_data_manager_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="privacy_officer",
            new_name="privacy_officer_conversation",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="data_manager",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="research_data_management",
        ),
        migrations.AddField(
            model_name="proposal",
            name="data_manager_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Als je geen datamanagementplan indient bij deze aanvraag,beantwoord deze vraag dan met 'nee'.",
                null=True,
                verbose_name="Ik heb mijn datamanagementplan (DMP) besproken met de data manager van de Faculteit Geesteswetenschappen.",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="research_data_management_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Als je geen datamanagementplan indient bij deze aanvraag,beantwoord deze vraag dan met 'nee'.",
                null=True,
                verbose_name="Ik heb mijn datamanagementplan (DMP) besproken met iemand van Research Data Management Support.",
            ),
        ),
    ]
