# Generated by Django 4.2.23 on 2025-07-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0061_alter_proposal_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="expected_end_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Wat is de beoogde einddatum waarop het onderzoek, waarvoor deze aanvraag wordt ingediend, verwacht wordt te zijn voltooid?",
            ),
        ),
    ]
