# Generated by Django 4.2.20 on 2025-05-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0061_alter_proposal_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="institution",
            field=models.ForeignKey(
                help_text="Algemene Kamer: OFR, OGK, ICON <br/>Linguïstiek Kamer: ILS",
                on_delete=django.db.models.deletion.PROTECT,
                to="proposals.institution",
                verbose_name="Aan welk onderzoeksinstituut ben je verbonden?",
            ),
        ),
    ]
