# Generated by Django 4.2.23 on 2025-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0061_alter_proposal_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="stakeholders",
            field=models.TextField(
                blank=True,
                help_text="Vul s.v.p. de naam en affiliatie (bijv. naam universiteit en land) van de niet-UU onderzoeker(s) in. Zie hierboven: het is van belang om na te gaan of met deze onderzoeker(s) persoonsgegevens van deelnemers gedeeld worden; in dat geval moet je contact opnemen met de privacy officer, zeker als deze onderzoeker(s) een affiliatie buiten de EU heeft/hebben.",
                verbose_name="Naam en affiliatie van andere betrokkenen",
            ),
        ),
    ]
