# Generated by Django 4.2.23 on 2026-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0063_alter_proposal_stakeholders"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="data_manager_conversation",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="privacy_officer_conversation",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="research_data_management_conversation",
        ),
        migrations.AddField(
            model_name="proposal",
            name="DMPChoice",
            field=models.PositiveIntegerField(
                choices=[
                    (
                        0,
                        "Het Data Management Plan (DMP) dat ik in de volgende stap zal indienen is besproken met en gezien door de datamanager van de faculteit Geesteswetenschappen.",
                    ),
                    (
                        1,
                        "Het Data Management Plan (DMP) dat ik in de volgende stap zal indienen is besproken met en gezien door iemand van Research Data Management Support.",
                    ),
                    (2, "Anders (licht s.v.p. toe)"),
                ],
                help_text="Contact: <a href='mailto:datamanagement.gw@uu.nl'>datamanager</a>",
                null=True,
                verbose_name="Data Management Plan",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="DMPChoice_details",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Toelichting",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="privacy_choice",
            field=models.PositiveIntegerField(
                choices=[
                    (
                        0,
                        "De documenten voor deelnemers die ik in de volgende stap zal indienen zijn besproken met en gezien door de privacy officer van de faculteit Geesteswetenschappen.",
                    ),
                    (
                        1,
                        "Op grond van kennis over privacy/de AVG en/of mijn ervaring kan ik bevestigen dat de documenten voor deelnemers die ik in de volgende stap zal indienen in orde zijn qua privacy/AVG.",
                    ),
                    (2, "Anders (licht s.v.p. toe)"),
                ],
                help_text="Contact: <a href='mailto:privacy.gw@uu.nl'>privacy officer</a>",
                null=True,
                verbose_name="Privacy/AVG",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="privacy_choice_details",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Toelichting",
            ),
        ),
    ]
