# Generated by Django 4.2.23 on 2025-11-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0063_alter_proposal_stakeholders"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="data_manager_conversation_comment",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Als dat niet gebeurd is, zou je dan willen toelichten waarom niet? Bijv. omdat vergelijkbare documenten van een eerdere aanvraag al zijn besproken met de datamanager (vermeld in dat geval s.v.p. het referentienummer).",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="privacy_officer_conversation_comment",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Als dat niet gebeurd is, zou je dan willen toelichten waarom niet? Bijv. omdat vergelijkbare documenten van een eerdere aanvraag al zijn besproken met de privacy officer (vermeld in dat geval s.v.p. het referentienummer).",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="research_data_management_conversation_comment",
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Als dat niet gebeurd is, zou je dan willen toelichten waarom niet? Bijv. omdat (vergelijkbare) documenten van een eerdere aanvraag al zijn besproken met Research Data Management Support of de datamanager (vermeld in dat geval s.v.p. het referentienummer).",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="data_manager_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Als je geen Data Management Plan indient bij deze aanvraag, beantwoord deze vraag dan met 'nee'.Contact: <a href='mailto:datamanagement.gw@uu.nl'>datamanager</a>",
                null=True,
                verbose_name="Het Data Management Plan (DMP) dat ik in de volgende stap indien is besproken met en gezien door de datamanager van de faculteit Geesteswetenschappen.",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="privacy_officer_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Contact: <a href='mailto:privacy.gw@uu.nl'>privacy officer</a>",
                null=True,
                verbose_name="De documenten voor deelnemers die ik in de volgende stap indien zijn besproken met en gezien door de privacy officer van de faculteit Geesteswetenschappen.",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="research_data_management_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Als je geen Data Management Plan indient bij deze aanvraag, beantwoord deze vraag dan met 'nee'.",
                null=True,
                verbose_name="Het Data Management Plan (DMP) dat ik hieronder indien is besproken met en gezien door iemand van Research Data Management Support.",
            ),
        ),
    ]
