# Generated by Django 4.2.23 on 2025-12-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0064_proposal_data_manager_conversation_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="data_manager_conversation_details",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Zou je dan willen toelichten waarom niet? Bijv. omdat (vergelijkbare) documenten van een eerdere aanvraag al zijn besproken met de datamanager (vermeld in dat geval s.v.p. het referentienummer).",
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="privacy_officer_conversation_details",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=500,
                null=True,
                verbose_name="Zou je dan willen toelichten waarom niet? Bijv. omdat (vergelijkbare) documenten van een eerdere aanvraag al zijn besproken met de Privacy Officier (vermeld in dat geval s.v.p. het referentienummer).",
            ),
        ),
    ]
