# Generated by Django 4.2.23 on 2026-01-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0064_remove_proposal_data_manager_conversation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="DMPChoice",
            new_name="dmp_choice",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="DMPChoice_details",
            new_name="dmp_choice_details",
        ),
    ]
