# Generated by Django 4.2.23 on 2025-11-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0064_proposal_data_manager_conversation_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="data_manager_conversation_comment",
            new_name="data_manager_conversation_details",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="privacy_officer_conversation_comment",
            new_name="privacy_officer_conversation_details",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="research_data_management_conversation_comment",
            new_name="research_data_management_conversation_details",
        ),
    ]
