# Generated by Django 4.2.27 on 2026-03-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("proposals", "0064_remove_proposal_data_manager_conversation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="reviewing_committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="auth.group",
                verbose_name="Door welke commissie dient deze aanvraag te worden beoordeeld?",
            ),
        ),
    ]
