# Generated by Django 4.2.23 on 2025-11-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proposals",
            "0065_rename_data_manager_conversation_comment_proposal_data_manager_conversation_details_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="data_manager_conversation",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Als je geen Data Management Plan indient bij deze aanvraag, beantwoord deze vraag dan met 'nee'.<br />Contact: <a href='mailto:datamanagement.gw@uu.nl'>datamanager</a>",
                null=True,
                verbose_name="Het Data Management Plan (DMP) dat ik in de volgende stap indien is besproken met en gezien door de datamanager van de Faculteit Geesteswetenschappen.",
            ),
        ),
    ]
