# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0005_review_date_should_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="go",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Y", "goedgekeurd"),
                    ("N", "niet goegekeurd"),
                    ("?", "revisie noodzakelijk"),
                ],
                max_length=1,
                verbose_name="Beslissing",
            ),
        ),
    ]
