# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-03 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0007_auto_20190401_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="continuation",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Goedkeuring door FETC-GW"),
                    (1, "Revisie noodzakelijk"),
                    (2, "Afwijzing door FETC-GW"),
                    (3, "Open review met lange (4-weken) route"),
                    (4, "Laat opnieuw beoordelen door METC"),
                    (5, "Positief advies van FETC-GW, post-hoc"),
                    (6, "Negatief advies van FETC-GW, post-hoc"),
                ],
                default=0,
                verbose_name="Afhandeling",
            ),
        ),
    ]
