# Generated by Django 2.2.17 on 2020-12-22 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0008_auto_20200428_1337"),
        ("reviews", "0008_auto_20201203_0906"),
    ]

    operations = []
