# Generated by Django 2.2.24 on 2021-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_merge_20201222_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='continuation',
            field=models.PositiveIntegerField(choices=[(0, 'Goedkeuring door FETC-GW'), (1, 'Revisie noodzakelijk'), (2, 'Afwijzing door FETC-GW'), (3, 'Open review met lange (4-weken) route'), (4, 'Laat opnieuw beoordelen door METC'), (5, 'Positief advies van FETC-GW, post-hoc'), (6, 'Negatief advies van FETC-GW, post-hoc'), (7, 'Niet verder in behandeling genomen door de FETC-GW')], default=0, verbose_name='Afhandeling'),
        ),
    ]
