# Generated by Django 2.2.24 on 2021-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0011_auto_20210920_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="go",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Y", "goedgekeurd"),
                    ("N", "niet goedgekeurd"),
                    ("?", "revisie noodzakelijk"),
                ],
                max_length=1,
                verbose_name="Beslissing",
            ),
        ),
    ]
