# Generated by Django 3.2.20 on 2023-11-14 09:46

from django.db import migrations, models

def update_is_commssion_review(apps, schema_editor):

    Review = apps.get_model('reviews', 'Review')

    for review in Review.objects.all():
        #Hardcoded this to account for possible future changes to stages
        SUPERVISOR_STAGE = 0
        if review.stage == SUPERVISOR_STAGE:
            review.is_commission_review = False
            review.update_go()
            review.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20211213_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_commission_review',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(update_is_commssion_review),
    ]
