# Generated by Django 3.2.14 on 2022-09-06 11:34

from django.db import migrations


def choose_review_type(apps, schema_editor):
    "Assign every review a type based on its stage."
    Review = apps.get_model("reviews", "Review")
    for review in Review.objects.all():
        print(f"Processing {review}")
        if review.stage == 0:
            review.review_type = "supervisor"
        else:
            review.review_type = "committee"
        review.save()


def choose_stage(apps, schema_editor):
    "Close all finished reviews of the supervisor type."
    Review = apps.get_model("reviews", "Review")
    for review in Review.objects.filter(review_type="supervisor"):
        if not review.decision_set.exists(go=""):
            review.stage = review.CLOSED
            # Otherwise, it will remain review.SUPERVISOR
        review.save()


def undo_choose_stage(apps, schema_editor):
    "Set all supervisor reviews to the same stage."
    Review = apps.get_model("reviews", "Review")
    for review in Review.objects.filter(review_type="supervisor"):
        review.stage = review.SUPERVISOR
        review.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_review_review_type'),
    ]

    operations = [
        migrations.RunPython(
            choose_review_type,
        ),
        migrations.RunPython(
            choose_stage,
            undo_choose_stage,
        ),
    ]
