# Generated by Django 4.2.11 on 2024-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0013_add_is_committee_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="comments",
            field=models.TextField(blank=True, verbose_name="Ruimte voor onderbouwing"),
        ),
    ]
