# Generated by Django 4.2.21 on 2025-05-20 12:04

from django.db import migrations

def run_update_go_when_no_date_end(apps, schema_editor):
    """
    Get all reviews with no date_end, and run update_go()    
    """
    Review = apps.get_model("reviews", "Review")
    for review in Review.objects.filter(date_end__is_null=True):
        review.update_go()
        review.save()


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0014_alter_decision_comments"),
    ]

    operations = [
        migrations.RunPython(run_update_go_when_no_date_end, reverse_code=migrations.RunPython.noop),
    ]
