# Generated by Django 4.2.23 on 2025-11-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0015_auto_20250527_1157"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="email_checkbox",
            field=models.BooleanField(default=False),
        ),
    ]
