# Generated by Django 2.2.24 on 2021-12-13 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210301_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='tasks_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='De totale geschatte netto taakduur van je sessie komt op basis van je opgave per taak uit op <strong>%d minuten</strong>. Hoe lang duurt <em>de totale sessie</em>, inclusief ontvangst, instructies per taak, pauzes tussen taken, en debriefing? (bij labbezoek dus van binnenkomst tot vertrek)'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tasks_number',
            field=models.PositiveIntegerField(help_text='Wanneer je bijvoorbeeld eerst de deelnemer observeert en de deelnemer vervolgens een vragenlijst afneemt, dan vul je hierboven "2" in. Electrodes plakken, sessie-debriefing en kort (< 3 minuten) exit-interview gelden niet als een taak.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Hoeveel taken worden er binnen deze sessie bij de deelnemer afgenomen?'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschrijf de taak die de deelnemer moet uitvoeren, en leg kort uit hoe deze taak (en de eventuele manipulaties daarbinnen) aan de beantwoording van jouw onderzoeksvragen bijdraagt. Geef, kort, een paar voorbeelden (of beschrijvingen) van het type stimuli dat je van plan bent aan de deelnemer aan te bieden. Het moet voor de commissieleden duidelijk zijn wat je precies gaat doen.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='feedback',
            field=models.BooleanField(blank=True, null=True, verbose_name='Krijgt de deelnemer tijdens of na deze taak feedback op hun gedrag of toestand?'),
        ),
    ]
