# Generated by Django 3.2.20 on 2024-01-30 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20240103_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tasks_number',
        ),
    ]
