# Generated by Django 4.2.11 on 2025-03-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_alter_session_tasks_duration_alter_task_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationkind",
            name="registration",
        ),
        migrations.RemoveField(
            model_name="task",
            name="registration_kinds",
        ),
        migrations.RemoveField(
            model_name="task",
            name="registration_kinds_details",
        ),
        migrations.RemoveField(
            model_name="task",
            name="registrations",
        ),
        migrations.RemoveField(
            model_name="task",
            name="registrations_details",
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
        migrations.DeleteModel(
            name="RegistrationKind",
        ),
    ]
