# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 09:29
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_auto_20180306_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='briefing',
            field=models.FileField(blank=True, upload_to='', validators=[core.validators.validate_pdf_or_doc], verbose_name='Upload hier de informatiebrief (in .pdf of .doc(x)-formaat)'),
        ),
        migrations.AlterField(
            model_name='study',
            name='deception',
            field=models.CharField(blank=True, choices=[('Y', 'ja'), ('N', 'nee'), ('?', 'twijfel')], help_text='Misleiding is het doelbewust verschaffen van inaccurate informatie over het doel en/of belangrijke aspecten van de gang van zaken tijdens de studie. Denk aan zaken als een bewust misleidende "cover story" voor het experiment; het ten onrechte suggereren dat er met andere deelnemers wordt samengewerkt; het onaangekondigd aanbieden van een cruciale geheugentaak of het geven van gefingeerde feedback. Wellicht ten overvloede: het gaat hierbij niet om fillers.', max_length=1, verbose_name='Is er binnen bovenstaand onderzoekstraject sprake van misleiding van de deelnemer?'),
        ),
        migrations.AlterField(
            model_name='study',
            name='director_consent_declaration',
            field=models.FileField(blank=True, help_text='If it is already signed, upload the signed declaration form. If it is not signed yet, you can upload the unsigned document and send the document when it is signed to the secretary of the EtCL', upload_to='', validators=[core.validators.validate_pdf_or_doc], verbose_name='Upload hier de toestemmingsverklaring van de schoolleider/hoofd van het departement (in .pdf of .doc(x)-format)'),
        ),
        migrations.AlterField(
            model_name='study',
            name='director_consent_information',
            field=models.FileField(blank=True, upload_to='', validators=[core.validators.validate_pdf_or_doc], verbose_name='Upload hier de informatiebrief voor de schoolleider/hoofd van het departement (in .pdf of .doc(x)-formaat)'),
        ),
        migrations.AlterField(
            model_name='study',
            name='informed_consent',
            field=models.FileField(blank=True, upload_to='', validators=[core.validators.validate_pdf_or_doc], verbose_name='Upload hier de toestemmingsverklaring (in .pdf of .doc(x)-formaat)'),
        ),
        migrations.AlterField(
            model_name='study',
            name='necessity',
            field=models.CharField(blank=True, choices=[('Y', 'ja'), ('N', 'nee'), ('?', 'twijfel')], help_text='Is het bijvoorbeeld noodzakelijk om kinderen te testen, of zou u de vraag ook kunnen beantwoorden door volwassen deelnemers te testen?', max_length=1, verbose_name='Is het, om de onderzoeksvraag beantwoord te krijgen, noodzakelijk om het geselecteerde type deelnemer aan de studie te laten meedoen?'),
        ),
        migrations.AlterField(
            model_name='study',
            name='negativity',
            field=models.CharField(blank=True, choices=[('Y', 'ja'), ('N', 'nee'), ('?', 'twijfel')], max_length=1, verbose_name='Bevat bovenstaand onderzoekstraject elementen die <em>tijdens</em> de deelname niet-triviale negatieve emoties kunnen opwekken? Denk hierbij bijvoorbeeld aan emotioneel indringende vragen, kwetsende uitspraken, negatieve feedback, frustrerende, zware, (heel) lange en/of (heel) saaie taken.'),
        ),
        migrations.AlterField(
            model_name='study',
            name='parents_information',
            field=models.FileField(blank=True, upload_to='', validators=[core.validators.validate_pdf_or_doc], verbose_name='Upload hier de informatiebrief voor de ouders (in .pdf of .doc(x)-formaat)'),
        ),
        migrations.AlterField(
            model_name='study',
            name='risk',
            field=models.CharField(blank=True, choices=[('Y', 'ja'), ('N', 'nee'), ('?', 'twijfel')], help_text='Achtergrondrisico is datgene dat gezonde, gemiddelde burgers in de relevante leeftijdscategorie normaalgesproken in het dagelijks leven ten deel valt. Denk bij schade ook aan de gevolgen die het voor de deelnemer of anderen beschikbaar komen van bepaalde informatie kan hebben, bijv. op het vlak van zelfbeeld, stigmatisering door anderen, economische schade door data-koppeling, et cetera. Het achtergrondrisico voor psychische en fysieke schade omvat bijvoorbeeld ook de risico\'s van "routine"-tests, -onderzoeken of -procedures die in alledaagse didactische, psychologische of medische contexten plaatsvinden (zoals een eindexamen, een rijexamen, een stressbestendigheids-<em>assessment</em>, een intelligentie- of persoonlijkheidstest, of een hartslagmeting na fysieke inspanning; dit alles, waar relevant, onder begeleiding van adequaat geschoolde specialisten).', max_length=1, verbose_name='Zijn de risico\'s op psychische, fysieke, of andere (bijv. economische, juridische) schade door deelname aan bovenstaand onderzoekstraject <em>meer dan</em> minimaal? D.w.z. ligt de kans op en/of omvang van mogelijke schade bij de deelnemers duidelijk <em>boven</em> het "achtergrondrisico"?'),
        ),
        migrations.AlterField(
            model_name='study',
            name='stressful',
            field=models.CharField(blank=True, choices=[('Y', 'ja'), ('N', 'nee'), ('?', 'twijfel')], help_text="Dit zou bijvoorbeeld het geval kunnen zijn bij een 'onmenselijk' lange en uitputtende taak, een zeer confronterende vragenlijst, of voortdurend vernietigende feedback, maar ook bij een ervaren inbreuk op de privacy, of een ander ervaren gebrek aan respect. Let op, het gaat bij deze vraag om de door de deelnemer ervaren belasting tijdens het onderzoek, niet om de opgelopen psychische of fysieke schade door het onderzoek.", max_length=1, verbose_name='Bevat bovenstaand onderzoekstraject elementen die tijdens de deelname zodanig belastend zijn dat deze <em>ondanks de verkregen informed consent</em> vragen zou kunnen oproepen (of zelfs verontwaardiging), bijvoorbeeld bij collega-onderzoekers, bij de deelnemers zelf, of bij ouders of andere vertegenwoordigers?'),
        ),
    ]
