# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0007_auto_20180808_1129"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agegroup",
            options={"ordering": ("age_min",)},
        ),
    ]
