# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0008_auto_20180808_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="agegroup",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
