# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 11:58
from __future__ import unicode_literals

from django.db import migrations


def migrate(apps, schema_editor):
    Study = apps.get_model("studies", "Study")
    Documents = apps.get_model("studies", "Documents")

    for study in Study.objects.all():
        d = Documents()
        d.study = study
        d.proposal = study.proposal
        d.informed_consent = study.informed_consent
        d.briefing = study.briefing
        d.director_consent_declaration = study.director_consent_declaration
        d.director_consent_information = study.director_consent_information
        d.parents_information = study.parents_information
        d.save()


def reverse(apps, schema_editor):
    Study = apps.get_model("studies", "Study")
    Documents = apps.get_model("studies", "Documents")

    for documents in Documents.objects.all():
        if not documents.study:
            print(
                "Could not restore {} as it's not connected to a study".format(
                    documents
                )
            )
            continue

        study = documents.study
        study.proposal = documents.proposal
        study.informed_consent = documents.informed_consent
        study.briefing = documents.briefing
        study.director_consent_declaration = documents.director_consent_declaration
        study.director_consent_information = documents.director_consent_information
        study.parents_information = documents.parents_information
        study.save()

        documents.delete()


class Migration(migrations.Migration):
    """
    This migrates data a study to the new documents model created in 0010_documents.py
    """

    dependencies = [
        ("studies", "0010_documents"),
    ]

    operations = [migrations.RunPython(migrate, reverse_code=reverse)]
