# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_auto_20180914_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='briefing',
        ),
        migrations.RemoveField(
            model_name='study',
            name='director_consent_declaration',
        ),
        migrations.RemoveField(
            model_name='study',
            name='director_consent_information',
        ),
        migrations.RemoveField(
            model_name='study',
            name='informed_consent',
        ),
        migrations.RemoveField(
            model_name='study',
            name='parents_information',
        ),
    ]
