# Generated by Django 2.2.24 on 2021-12-13 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0018_auto_20210409_1211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="age_groups",
            field=models.ManyToManyField(
                help_text="De beoogde leeftijdsgroep kan zijn 5-7 jarigen. Dan moet je hier hier 4-5 én 6-11 invullen.",
                to="studies.AgeGroup",
                verbose_name="Uit welke leeftijdscategorie(ën) bestaat je deelnemersgroep?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="compensation",
            field=models.ForeignKey(
                blank=True,
                help_text="Het standaardbedrag voor vergoeding aan de deelnemers is €10,- per uur. Minderjarigen mogen geen geld ontvangen, maar wel een cadeautje.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studies.Compensation",
                verbose_name="Welke vergoeding krijgt de deelnemer voor hun deelname?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="deception",
            field=models.CharField(
                blank=True,
                choices=[("Y", "ja"), ("N", "nee"), ("?", "twijfel")],
                help_text='Misleiding is het doelbewust verschaffen van inaccurate informatie over het doel en/of belangrijke aspecten van de gang van zaken tijdens het onderzoek. Denk aan zaken als een bewust misleidende "cover story" voor het experiment; het ten onrechte suggereren dat er met andere deelnemers wordt samengewerkt; het onaangekondigd aanbieden van een cruciale geheugentaak of het geven van gefingeerde feedback. Wellicht ten overvloede: het gaat hierbij niet om fillers.',
                max_length=1,
                verbose_name="Is er binnen bovenstaand onderzoekstraject sprake van misleiding van de deelnemer?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="has_traits",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Deelnemers kunnen geïncludeerd worden op bepaalde bijzondere kenmerken. Is dit in jouw onderzoek bij (een deel van) de deelnemers het geval?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="legally_incapable",
            field=models.BooleanField(
                default=False,
                help_text="Wilsonbekwame volwassenen zijn volwassenen waarvan redelijkerwijs mag worden aangenomen dat ze onvoldoende kunnen inschatten wat hun eventuele deelname allemaal behelst, en/of waarvan anderszins mag worden aangenomen dat informed consent niet goed gerealiseerd kan worden (bijvoorbeeld omdat ze niet goed hun eigen mening kunnen geven). Hier dient in ieder geval altijd informed consent van een relevante vertegenwoordiger te worden verkregen.",
                verbose_name="Maakt je onderzoek gebruik van wils<u>on</u>bekwame (volwassen) deelnemers?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="necessity",
            field=models.CharField(
                blank=True,
                choices=[("Y", "ja"), ("N", "nee"), ("?", "twijfel")],
                help_text="Is het bijvoorbeeld noodzakelijk om kinderen te testen, of zou je de vraag ook kunnen beantwoorden door volwassen deelnemers te testen?",
                max_length=1,
                verbose_name="Is het, om de onderzoeksvraag beantwoord te krijgen, noodzakelijk om het geselecteerde type deelnemer aan het onderzoek te laten meedoen?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="negativity_details",
            field=models.TextField(blank=True, verbose_name="Licht je antwoord toe."),
        ),
        migrations.AlterField(
            model_name="study",
            name="passive_consent",
            field=models.BooleanField(
                blank=True,
                help_text='Wanneer je kinderen via een instelling (dus ook school) werft en je de ouders niet laat ondertekenen, maar in plaats daarvan de leiding van die instelling, dan maak je gebruik van passieve informed consent. Je kan de templates vinden op <a href="https://intranet.uu.nl/documenten-ethische-toetsingscommissie-gw" target="_blank">de FETC-GW-website</a>.',
                null=True,
                verbose_name="Maak je gebruik van passieve informed consent?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="passive_consent_details",
            field=models.TextField(
                blank=True,
                verbose_name="Licht je antwoord toe. Wij willen je wijzen op het reglement, sectie 3.1 'd' en 'e'. Passive consent is slechts in enkele gevallen toegestaan en draagt niet de voorkeur van de commissie.",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="sessions_number",
            field=models.PositiveIntegerField(
                help_text="Wanneer je bijvoorbeeld eerst de deelnemer een taak/aantal taken laat doen tijdens een eerste bezoek aan het lab en je laat de deelnemer nog een keer terugkomen om dezelfde taak/taken of andere taak/taken te doen, dan spreken we van twee sessies. Wanneer je meerdere taken afneemt op dezelfde dag, met pauzes daartussen, dan geldt dat toch als één sessie.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Hoeveel sessies met taakonderzoek zullen de deelnemers doorlopen?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="stressful_details",
            field=models.TextField(
                blank=True,
                verbose_name="Licht je antwoord toe. Geef concrete voorbeelden van de relevante aspecten van jouw onderzoek (bijv. representatieve voorbeelden van mogelijk zeer kwetsende woorden of uitspraken in de taak, of van zeer confronterende vragen in een vragenlijst), zodat de commissie zich een goed beeld kan vormen.",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="traits",
            field=models.ManyToManyField(
                blank=True,
                to="studies.Trait",
                verbose_name="Selecteer de bijzondere kenmerken van je proefpersonen",
            ),
        ),
    ]
