# Generated by Django 3.2.13 on 2022-06-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0019_auto_20211213_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='self_assesment',
            field=models.TextField(blank=True, max_length=500, verbose_name='PLACEHOLDER QUESTION FOR SELF ASSESMENT'),
        ),
    ]
