# Generated by Django 3.2.13 on 2022-06-24 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0020_study_self_assesment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="study",
            name="self_assesment",
        ),
    ]
