# Generated by Django 3.2.13 on 2022-12-06 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studies", "0024_alter_study_has_traits"),
        ("studies", "0024_auto_20221018_1653"),
    ]

    operations = []
