# Generated by Django 3.2.14 on 2022-11-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0024_alter_study_has_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='passive_consent',
        ),
        migrations.RemoveField(
            model_name='study',
            name='passive_consent_details',
        ),
    ]
