# Generated by Django 3.2.13 on 2023-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0025_merge_20221206_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='traits',
            field=models.ManyToManyField(blank=True, to='studies.Trait', verbose_name='Selecteer de medische gegevens van je proefpersonen die worden verzameld'),
        ),
    ]
