# Generated by Django 4.2.11 on 2024-10-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0029_remove_study_stressful_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="study",
            name="legal_basis",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "Dit traject is volledig anoniem."),
                    (1, "De deelnemers geven toestemming."),
                    (2, "De AVG grondslag is algemeen belang."),
                ],
                help_text="Voor meer informatie over welk AVG grondslag op jouw onderzoek van toepassing is, zie de flowchart in het <a href='https://utrechtuniversity.github.io/dataprivacyhandbook/choose-legal-basis.html' target='_blank'>Data Privacy Handbook</a>",
                null=True,
                verbose_name="Wat is de AVG grondslag voor het verzamelen van persoonsgegevens?",
            ),
        ),
    ]
