# Generated by Django 4.2.11 on 2024-12-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0030_study_legal_basis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="has_sessions",
            field=models.BooleanField(
                default=False, verbose_name="Taakonderzoek en/of interview(s)"
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="has_special_details",
            field=models.BooleanField(
                blank=True,
                help_text="Wat 'bijzondere of gevoelige persoonsgegevens' zijn kun je vinden op <a href='https://utrechtuniversity.github.io/dataprivacyhandbook/special-types-personal-data.html#special-types-personal-data' target='_blank'>deze pagina</a> van het UU Data Privacy Handbook.",
                null=True,
                verbose_name="Worden er bijzondere of gevoelige persoonsgegevens verzameld?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="legal_basis",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "Dit traject is volledig anoniem."),
                    (1, "De AVG grondslag is 'algemeen belang'."),
                    (2, "De AVG grondslag is 'toestemming'."),
                ],
                help_text="Voor meer informatie over welk AVG grondslag op jouw onderzoek van toepassing is, zie de flowchart in het <a href='https://utrechtuniversity.github.io/dataprivacyhandbook/choose-legal-basis.html' target='_blank'>UU Data Privacy Handbook</a>",
                null=True,
                verbose_name="Wat is de AVG grondslag voor het verzamelen van persoonsgegevens?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="legally_incapable",
            field=models.BooleanField(
                default=False,
                help_text="Wilsonbekwame volwassenen zijn volwassenen waarvan redelijkerwijs mag worden aangenomen dat ze onvoldoende kunnen inschatten wat hun eventuele deelname allemaal behelst, en/of waarvan anderszins mag worden aangenomen dat bewuste toestemming niet goed gerealiseerd kan worden (bijvoorbeeld omdat ze niet goed hun eigen mening kunnen geven). Hier dient in ieder geval altijd toestemming van een relevante vertegenwoordiger te worden verkregen.",
                verbose_name="Maakt je onderzoek gebruik van wils<u>on</u>bekwame volwassen deelnemers?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="passive_consent",
            field=models.BooleanField(
                blank=True,
                help_text='Wanneer je kinderen via een instelling (dus ook school) werft en je de ouders niet laat ondertekenen, maar in plaats daarvan de leiding van die instelling, dan maak je gebruik van passieve toestemming. Je kan de templates vinden op <a href="https://intranet.uu.nl/documenten-ethische-toetsingscommissie-gw" target="_blank">de FETC-GW-website</a>.',
                null=True,
                verbose_name="Maak je gebruik van passieve toestemming?",
            ),
        ),
        migrations.AlterField(
            model_name="study",
            name="recruitment_details",
            field=models.TextField(blank=True, verbose_name="Licht toe"),
        ),
    ]
