# Generated by Django 4.2.11 on 2024-12-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0031_alter_study_has_sessions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Naam traject"
            ),
        ),
    ]
