# Generated by Django 4.2.20 on 2025-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0033_alter_documents_informed_consent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="risk_details",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Licht toe"
            ),
        ),
    ]
