# Generated by Django 4.2.20 on 2025-05-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0034_alter_study_risk_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="negativity_details",
            field=models.TextField(
                blank=True,
                help_text="Geef concrete voorbeelden van de relevante aspecten van jouw onderzoek (bijv. voorbeelden van mogelijk zeer kwetsende woorden of uitspraken in de taak; zeer confronterende vragen in een vragenlijst; negatieve feedback), zodat de commissie zich een goed beeld kan vormen.",
                max_length=1000,
                verbose_name="Licht toe",
            ),
        ),
    ]
