# Generated by Django 4.2.17 on 2025-03-26 13:04

from django.db import migrations
from django.core.management import call_command

#Custom migration to load new fixtures for Registration model

def load_fixtures(apps, schema_editor):
    call_command("load_fixtures")

class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0034_registration_study_registration_kinds_details_and_more"),
    ]

    operations = [
        migrations.RunPython(load_fixtures, migrations.RunPython.noop),
    ]
