# Generated by Django 4.2.17 on 2025-03-26 13:04

from django.db import migrations
from django.core.management import call_command

# Custom migration to load new fixtures for Registration model


registration_fixtures = "00_registrations", "01_registrationkinds"


def load_registration_fixtures(apps, schema_editor):
    for fixture in registration_fixtures:
        call_command("loaddata", fixture, app_label="studies")


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0036"
        "_registration_study_registration_kinds_details_and_more"),
    ]

    operations = [
        migrations.RunPython(load_registration_fixtures, migrations.RunPython.noop),
    ]
