# Generated by Django 3.2.17 on 2023-09-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='')),
                ('kind', models.CharField(choices=[('information_letter', 'Informatiebrief'), ('consent_form', 'Toestemmingsverklaring'), ('dmp', 'Data Management Plan')], default=('', 'Gelieve selecteren'), max_length=100)),
                ('name', models.CharField(default='', help_text='Geef je bestand een omschrijvende naam, het liefst één of twee woorden.', max_length=50)),
                ('comments', models.TextField(default='', help_text='Geef hier je motivatie om dit bestand toe te voegen en waar je het voor gaat gebruiken tijdens je onderzoek. Eventuele opmerkingen voor de FETC kun je hier ook kwijt.', max_length=2000)),
            ],
        ),
    ]
