# Generated by Django 4.2.11 on 2024-09-23 16:33

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studies", "0028_remove_study_sessions_number"),
        ("proposals", "0053_auto_20240201_1557"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_to",
                    models.ManyToManyField(
                        related_name="attachments", to="studies.study"
                    ),
                ),
            ],
            bases=(attachments.models.Attachment, models.Model),
        ),
        migrations.CreateModel(
            name="ProposalAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attached_to",
                    models.ManyToManyField(
                        related_name="attachments", to="proposals.proposal"
                    ),
                ),
            ],
            bases=(attachments.models.Attachment, models.Model),
        ),
    ]
