# Generated by Django 3.2.17 on 2024-03-15 12:42

import cdh.files.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210921_1014'),
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='attachments.attachment'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('information_letter', 'Informatiebrief'), ('consent_form', 'Toestemmingsverklaring'), ('dmp', 'Data Management Plan'), ('other', 'Overige bestanden')], default=('', 'Gelieve selecteren'), max_length=100),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(default='', help_text='Geef je bestand een omschrijvende naam, het liefst maar enkele woorden.', max_length=50),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='upload',
            field=cdh.files.db.fields.FileField(filename_generator=cdh.files.db.fields._default_filename_generator, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
