# Generated by Django 4.2.11 on 2024-10-01 13:43

import cdh.files.db.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0004_auto_20210921_1014"),
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="upload",
            field=cdh.files.db.fields.FileField(
                filename_generator=cdh.files.db.fields._default_filename_generator,
                help_text="Selecteer hier het bestand om toe te voegen.",
                on_delete=django.db.models.deletion.CASCADE,
                to="files.file",
                verbose_name="Bestand",
            ),
        ),
    ]
