# Generated by Django 3.2.17 on 2024-03-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0054_proposal_attachments'),
        ('attachments', '0002_auto_20240315_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attached_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_attachments_set', to='proposals.proposal'),
        ),
    ]
