# Generated by Django 3.2.17 on 2024-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0054_proposal_attachments'),
        ('attachments', '0003_attachment_attached_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attached_to',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attached_to',
            field=models.ManyToManyField(null=True, related_name='attachments_set', to='proposals.Proposal'),
        ),
    ]
