# Generated by Django 4.2.11 on 2024-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0003_alter_attachment_comments_alter_attachment_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="kind",
            field=models.CharField(default=("", "Gelieve selecteren"), max_length=100),
        ),
    ]
