# Generated by Django 4.2.11 on 2024-11-25 11:18

import attachments.utils
import cdh.files.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_auto_20210921_1014"),
        ("attachments", "0004_alter_attachment_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="kind",
            field=models.CharField(
                default=("other", "Overig bestand"),
                max_length=100,
                verbose_name="Type bestand",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="upload",
            field=cdh.files.db.fields.FileField(
                filename_generator=attachments.utils.attachment_filename_generator,
                help_text="Selecteer hier het bestand om toe te voegen.",
                on_delete=django.db.models.deletion.CASCADE,
                to="files.file",
                verbose_name="Bestand",
            ),
        ),
    ]
