# Generated by Django 4.2.11 on 2024-11-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0004_alter_attachment_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="kind",
            field=models.CharField(
                default=("other", "Overig bestand"),
                max_length=100,
                verbose_name="Type bestand",
            ),
        ),
    ]
