name: Check for missing migrations

on:
  pull_request:
jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libldap2-dev libsasl2-dev libssl-dev gettext poppler-utils poppler-data libpoppler-cpp-dev
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check for missing migrations
        run: |
          python manage.py makemigrations --check --dry-run
